platform :ios, '8.0'

target 'BlocQuery' do
  pod 'Parse'
  pod 'ParseUI'
  pod 'MBProgressHUD', '~> 0.9.1'
  pod 'Underscore.m'
  pod 'FontAwesomeKit/FontAwesome'
  pod 'GRMustache', '~> 7.3.2'
  pod 'RSKImageCropper'
  pod 'DBCamera', '~> 2.4'
end

target 'BlocQueryTests' do

end
